# Generated by Django 6.1 on 2026-09-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
