# Generated by Django 6.1 on 2026-09-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
