# Generated by Django 6.1 on 2026-09-03 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
