# Generated by Django 6.1 on 2026-09-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='device_id',
            new_name='device',
        ),
    ]
