# Generated by Django 6.1 on 2026-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_rename_device_id_state_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='units',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
