# Generated by Django 6.1 on 2026-09-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_device_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='device',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
