# Generated by Django 6.1 on 2026-09-06 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0012_remove_state_device_delete_reading_delete_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('units', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=200, unique=True)),
                ('metadata', models.JSONField(default=dict)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external', to='sensors.datastream')),
            ],
        ),
        migrations.CreateModel(
            name='LocalStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal', to='sensors.datastream')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('observed_at', models.DateTimeField()),
                ('measurements', models.JSONField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.datastream')),
            ],
        ),
    ]
