# Generated by Django 6.1 on 2026-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstream',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
