# Generated by Django 6.1 on 2026-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_localstream_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
