# Generated by Django 6.1 on 2026-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_datastream_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastream',
            old_name='units',
            new_name='metrics',
        ),
    ]
