# Generated by Django 6.1 on 2026-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_rename_units_datastream_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalstream',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='localstream',
            name='metadata',
        ),
        migrations.AddField(
            model_name='datastream',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
