# Generated by Django 6.1 on 2026-09-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_remove_externalstream_metadata_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['stream', 'observed_at'], name='reading_stream_observed_idx'),
        ),
    ]
