# Generated by Django 6.1 on 2026-09-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_reading_reading_stream_observed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstream',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
